spring:
  application:
    name: SandboxTemplate

  security:
    user:
      name: admin
      password: demo

# Expose shutdown endpoint 
# enable actuator to include shutdown
management:
  endpoints:
    web:
      exposure:
        include: shutdown
      base-path: /actuator
  endpoint:
    shutdown:
      enabled: true
