spring:
  application:
    name: actdemo

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env: { enabled: true }
    java: { enabled: true }
    os: { enabled: true }

info:
  app:
    name: @project.name@
    description: @description@
    version: @version@
    custom-property: put value here