webapi:
  security:
    # Values are DegradedSecurity (for anonymous access) and RegularSecurity.
    provider: RegularSecurity

spring:
  application:
    name: secdemo

logging:
  level:
    org.springframework.security: TRACE
